server:
  port: 8081
spring:
  application:
    name: ES
  elasticsearch:
    address: 116.204.69.134:9200
    ip: 116.204.69.134
    port: 9200
    pool: 5

  datasource:
    druid:
     #url: jdbc:mysql://49.232.135.90:3306/Inkbook?allowMultiQueries=true # 暂时用远程，在部署时IP地址改成127.0.0.1
      url: jdbc:mysql://116.204.69.134:31000/ace_database?allowMultiQueries=true
      username: root
      password: 7igePMdVWr3JQXQ
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    servlet:
      load-on-startup: 1
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com;163邮箱是smtp.163.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    #端口
    port: 25
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: acegateadmin@163.com
    #授权码
    password: NXKTEZRZLUKRTBYU
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

